services:
  jenkins-docker:
    image: docker:27.0.3-dind-alpine3.20
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    ports:
      - 2376:2376
    command:
      - --storage-driver=overlay2

  jenkins-blueocean:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 5000:5000
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    restart: on-failure
    networks:
      - jenkins

volumes:
  jenkins-data: {}
  jenkins-docker-certs: {}

networks:
  jenkins: {}